export enum ResponseType {
    RES_TYPE_NO_DEVICE_ATTACHED = "NO_DEVICE_ATTACHED",
    RES_TYPE_DEVICE_CONNECTION_OPENED = "DEVICE_CONNECTION_OPENED",
    RES_TYPE_DEVICE_CONNECTION_CLOSED = "DEVICE_CONNECTION_CLOSED",
    RES_TYPE_DEVICE_CONNECTION_ERROR = "DEVICE_CONNECTION_ERROR",
    RES_TYPE_TAG_INFO = "TAG_INFO",
    RES_TYPE_ERROR = "ERROR"
}

export enum TagType {
    UNKNOWN = "UNKNOWN",
    MIFARE_CLASSIC_1K = "MIFARE_CLASSIC_1K",
    MIFARE_CLASSIC_4K = "MIFARE_CLASSIC_4K",
    MIFARE_ULTRALIGHT = "MIFARE_ULTRALIGHT",
    MIFARE_MINI = "MIFARE_MINI",
    TOPAZ_JEWEL = "TOPAZ_JEWEL",
    FELICA_212K = "FELICA_212K",
    FELICA_424K = "FELICA_424K",
    NFCIP = "NFCIP",
    DESFIRE_EV1 = "DESFIRE_EV1"
}



